name: Build

on:
  push:
    branches: [main, "*.x"]

jobs:

  build:
    runs-on: ubuntu-latest
    env:
      MAVEN_ARGS: --batch-mode --color=always --no-transfer-progress --settings=.github/settings.xml
    steps:
      - run: git config --global user.name "${{ vars.KOKUWA_IO_BOT_NAME }}"
      - run: git config --global user.email "${{ vars.KOKUWA_IO_BOT_EMAIL }}"
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GIT_ACTION_TOKEN }}
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
      - run: mvn $MAVEN_ARGS dependency:go-offline
      - run: mvn $MAVEN_ARGS deploy
        env:
          SERVER_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
      - run: mvn $MAVEN_ARGS site-deploy
        env:
          GIT_ACTION_TOKEN: ${{ secrets.GIT_ACTION_TOKEN }}
