name: PullRequest

"on": pull_request

jobs:

  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
          cache: maven
      - run: mvn -B dependency:go-offline
      - run: mvn -B verify
      - uses: dorny/test-reporter@v1.5.0
        if: failure()
        with:
          name: surefire
          path: '**/target/surefire-reports/*.xml,**/target/invoker-reports/*.xml'
          reporter: java-junit
          list-suites: failed
          list-tests: failed
          fail-on-error: false
